version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "auto"
    commit_message:
      prefix: "build"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"
