name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install
      run: make install
    - name: Test
      env:
        CI: 1
        DB_NAME: jogger
        DB_TEST: jogger.test
        SECRET: 'random-test-django-secret-key-string'
        SMTP_HOST: localhost
        SMTP_USER: 1052
      run: |
        make database
        make coverage
    - name: Report
      if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m coveralls --service=github
